### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by NaufalFajri** [kotori2/llas_master_db_diff#1]
I'm new here, how to decrypt these files?

**Comment by kotori2** [comment]
> How to use this?

It just a repo to check what did they updated in database

> how to decrypt these files?

You can easily find a decryptor on GitHub.

**Comment by NaufalFajri** [comment]
idk where gonna find decrypt tool :< (seriously)

**Comment by kotori2** [comment]
@NaufalFajri Can't help
